package models

import (
	external_models "github.com/ogdans3/i-hate-kubernetes/code/i-hate-kubernetes/models/external-models"
)

type Service struct {
	Id            string //An ID generated by this program in order to attach services to containers
	ServiceName   string //The name of this service, specified by the key in yaml
	Image         string //The docker image to use
	Build         string //A build command which will be used during development
	Dev           string //A dev command?
	Watch         string //No idea?
	ContainerName string //The name for this container, will appear in docker ps
	FullName      string //The name for this container, will appear in docker ps

	Www       bool      //Should requests be redirected from example.com to www.example.com
	Https     bool      //Should https be used
	Ports     []Port    //A list of port mappings
	Autoscale Autoscale //Autoscaling settings for this pod
}

func ParseService(service *external_models.Service, projectId string) *Service {
	return &Service{
		Id:            projectId + "-" + service.ServiceName,
		ServiceName:   service.ServiceName,
		Image:         service.Image,
		Build:         service.Build,
		Dev:           service.Dev,
		Watch:         service.Watch,
		ContainerName: service.ContainerName,
		FullName:      service.FullName,

		Www:       service.Www,
		Https:     service.Https,
		Ports:     ParsePorts(service.Ports),
		Autoscale: ParseAutoscale(service.Autoscale),
	}
}

func ParseServices(unparsedServices map[string]*external_models.Service, projectId string) map[string]*Service {
	services := map[string]*Service{}
	for key, service := range unparsedServices {
		services[key] = ParseService(service, projectId)
	}
	return services
}
